apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills
  namespace: ingress-nginx
  labels:
    app: skills
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skills
  template:
    metadata:
      labels:
        app: skills
    spec:
      containers:
      - name: skills
        image: nguyenvancongdev/skills
        ports:
        - containerPort: 80
